{
  parserClass="io.github.potjerodekool.nabuidea.language.parser.NabuParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Nabu"
  psiImplClassSuffix="Impl"
  psiPackage="io.github.potjerodekool.nabuidea.language.psi"
  psiImplPackage="io.github.potjerodekool.nabuidea.language.psi.impl"

  elementTypeHolderClass="io.github.potjerodekool.nabuidea.language.psi.NabuTypes"
  elementTypeClass="io.github.potjerodekool.nabuidea.language.psi.NabuElementType"
  tokenTypeClass="io.github.potjerodekool.nabuidea.language.psi.NabuTokenType"
  psiImplUtilClass="io.github.potjerodekool.nabuidea.language.psi.impl.NabuPsiImplUtil"
}

nabuFile ::= compilationUnit

compilationUnit ::= ordinaryCompilationUnit

ordinaryCompilationUnit ::= packageDeclaration?
topLevelClassOrInterfaceDeclaration*

packageDeclaration ::= PACKAGE IDENTIFIER (DOT IDENTIFIER)* SEMI_COLON COMMENT?

topLevelClassOrInterfaceDeclaration ::=
normalClassDeclaration

normalClassDeclaration ::= classModifier* CLASS typeIdentifier classBody

classModifier ::=
PUBLIC
| PROTECTED
| PRIVATE
| ABSTRACT
| STATIC
| FINAL
| SEALED
| NON_SEALED
| STRICTFP

typeIdentifier ::= IDENTIFIER

classBody ::=
LBRACE
RBRACE